#I "./packages/Akka/lib/net45/"
#I "./packages/Newtonsoft.Json/lib/net45/"
#I "./packages/FsPickler/lib/net45/"
#I "./packages/FSPowerPack.Linq.Community/lib/net40/"
#I "./packages/Akka.FSharp/lib/net45/"
#I "./packages/Suave/lib/net40/"
#I "/Users/tomasjansson/git/suave/src/Experimental/bin/Release"
//#I "./packages/Suave.Experimental/lib/net40/"
#I "./packages/FSharp.Data/lib/net40"

#r "Suave.dll"
#r "Suave.Experimental.dll"
#r "Newtonsoft.Json.dll"
#r "Akka.dll"
#r "FsPickler.dll"
#r "FSharp.PowerPack.Linq.dll"
#r "Akka.FSharp.dll"
#r "FSharp.Data"
