#I "./packages/FSharp.Core/lib/net40/"
#I "./packages/Suave/lib/net40/"
//#I "./packages/Suave.Experimental/lib/net40/"
#I "/Users/tomasjansson/git/suave/src/Experimental/bin/Release"
#I "./packages/Newtonsoft.Json/lib/net45"

#r "FSharp.Core.dll"
#r "Suave.dll"
#r "Suave.Experimental.dll"
#r "Newtonsoft.Json.dll"
